#!/bin/sh

exec 2>&1

echo "=== Starting darkhttpd: $(date)"
exec darkhttpd /apps/diegoalban/public \
  --no-server-id \
  --no-keepalive \
  --uid _darkhttpd --gid _darkhttpd \
  --no-listing \
  --chroot \
  --maxconn 10
