user: nobody
listen: 80
hosts:
  "surferhearts.com:80":
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:81/
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
    listen:
      port: 443
      ssl:
        key-file: /progs/http/certbot/live/www.surferhearts.com/privkey.pem
        certificate-file: /progs/http/certbot/live/www.surferhearts.com/fullchain.pem
  "www.surferhearts.com:80":
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:81/
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
    listen:
      port: 443
      ssl:
        key-file: /progs/http/certbot/live/www.surferhearts.com/privkey.pem
        certificate-file: /progs/http/certbot/live/www.surferhearts.com/fullchain.pem
  "diegoalban.com:80":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
  "www.diegoalban.com:80":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge/":
        file.dir: /progs/http/acme/.well-known/acme-challenge
  "miniuni.com:80":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
  "www.miniuni.com:80":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
  "www.miniuni.com:443":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
  "megauni.com:80":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge
  "www.megauni.com:80":
    paths:
      "/":
        file.dir: /apps/diegoalban/public
      "/.well-known/acme-challenge":
        file.dir: /progs/http/acme/.well-known/acme-challenge

access-log: /progs/logs/h2o.access
error-log: /progs/logs/h20.error
