#!/usr/bin/env bash
# Instructions:
#   https://alpha.de.repo.voidlinux.org/live/current/void-x86_64-ROOTFS-20210218.tar.xz
#   Use visudo to edit sudoers file.
# Install rsync. Then upload this file to server and execute.
#
set -u -e -o pipefail
THE_ARGS="$@"
THIS_DIR="$( dirname "$(realpath "$0")" )/.."


set -x
sudo xbps-install -Suv
sudo xbps-install -S git tree neovim fish-shell rsync htop wget curl

set +x
for x in 3 4 5 6; do
  sv_name="/var/service/agetty-tty$x"
  if test -e "$sv_name" ; then
    echo "=== Removing: $sv_name"
    sudo rm "$sv_name"
  fi
done

set +x
if ! test -e /progs ; then
  echo "=== Creating /progs"
  mkdir -p $HOME/progs
  sudo ln -s $HOME/progs /progs
fi

fish_dir=$HOME/.config/fish
if ! test -L "$fish_dir" ; then
  echo "=== Setting up $fish_dir"
  test -e "$fish_dir" && mv $fish_dir ${fish_dir}.old || :
  ln -s $HOME/progs/my-bdrm-01/config/fish "$fish_dir"
  tree "$fish_dir"
fi


mkdir -p /progs/crystal
cd /progs/crystal
c_ver="1.0.0-1"
c_folder="crystal-$c_ver"
if test -e "$c_folder" ; then
  crystal --version
else
  c_url="https://github.com/crystal-lang/crystal/releases/download/1.0.0/crystal-1.0.0-1-linux-x86_64.tar.gz"
  c_archive="$(basename "$c_url")"
  set -x
  wget --continue "$c_url"
  tar -xvf "$c_archive"
  rm -f "$PWD/current"
  ln -s "$PWD/$c_folder" "$PWD/current"
  set +x
fi

set -x
cd "$THIS_DIR"

